login/urls.py
# from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import user_logout,user_login

app_name = 'login'

urlpatterns = [
        url(r'^$',user_login,name='login'),
        url(r'^logout',user_logout,name='logout'),
]

manager/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static

app_name = 'manager'

urlpatterns = [
#cashier/
    url(r'^$',views.index,name='index'),
    url(r'^user/$',views.user_profile,name='user_profile'),
    url(r'^managecashiers/$',views.managecashiers,name='manage_cashiers'),
    url(r'^transaction/$',views.transaction,name='transaction'),
    url(r'^addtask/$',views.addtask,name='addTask'),
    url(r'^addEmployee/$',views.addEmployee,name='addEmployee'),
    url(r'^managestock/$',views.managestock,name='managestock'),
    url(r'^delete/(?P<taskId>[0-9]+)/$',views.deleteTask,name='deleteTask'),



]

supermarket/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^cashier/', include('cashier.urls')),
    url(r'^manager/',include('manager.urls')),
    url(r'^',include('login.urls')),
    url(r'^admin/', admin.site.urls),
]

manager/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    First_Name =  models.CharField(max_length = 50)
    Last_Name =  models.CharField(max_length = 50)
    Address =  models.CharField(max_length = 45)
    Contact= models.CharField(max_length = 14)
    Country= models.CharField(max_length = 25)
    Salary = models.CharField(max_length = 8)

    def __str__(self):
        return self.First_Name +' '+ self.Last_Name

# class Cashier(Employee):
#     password =  models.CharField(max_length = 250)
#     username = models.CharField(max_length = 250)

class Tasks(models.Model):
    Task =  models.CharField(max_length = 250)

    def __str__(self):
        return self.Task

manager/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from .models import Tasks, Employee
from .functions import save_employee, findsalespermonth, findpurchasespermonth, findsalesoverpeiod, findpurchasesoverpeiod
from cashier.models import Products , Sales , Purchases
from datetime import datetime, date
from django.contrib import messages
from django.db.models import Count , Sum , Avg, Q, F, Min
from django.db.models.functions import TruncMonth, TruncYear



# Create your views here.
@login_required
def index(request):
    username = request.session['username']
    Currenttasks = Tasks.objects.all()
    Employees = Employee.objects.all()
    return render(request,'manager/dashboard.html',{'Currenttasks':Currenttasks, 'Employees':Employees,'username':username})

@login_required
def user_profile(request):
    username = request.session['username']
    return render(request,'manager/user_profile.html',{'username':username})

@login_required
def managecashiers(request):
    username = request.session['username']
    users = User.objects.all()
    return render(request,'manager/managecashiers.html',{'users':users,'username':username})

@login_required
def transaction(request):
    username = request.session['username']
    sales_per_month = findsalespermonth()
    purchases_per_month = findpurchasespermonth()

    # print(purchases_per_month)
    return render(request,'manager/transaction.html',{'sales_per_month':sales_per_month, 'purchases_per_month':purchases_per_month,'username':username})

@login_required
def addtask(request):
    if request.method =='POST':
         newtask = Tasks()
         newtask.Task = request.POST['task']
         newtask.save()
         return HttpResponseRedirect(reverse('manager:index'))


@login_required
def addEmployee(request):
    if request.method =='POST':
        save_employee(request.POST)
        return HttpResponseRedirect(reverse('manager:index'))

@login_required
def deleteTask(request, taskId):
    Tasks.objects.get(id=taskId).delete()
    return HttpResponseRedirect(reverse('manager:index'))

@login_required
def managestock(request):
    context = {}
    if request.method=='GET':
            return render(request,'manager/viewstock.html')
    else:
        from_date = request.POST['from']
        # to_date = request.POST['to']
        to_date =  str(date.today())

        sales_status_as_of = findsalesoverpeiod(from_date , to_date)
        product_status_as_of = findpurchasesoverpeiod(from_date, to_date)
        # red=product_status_as_of.filter(name='Coco-butter')
        items=[]
        # i=0
        for item in Products.objects.annotate(min_purchasedate = Min('purchases__date_of_purchase')).filter(min_purchasedate__lte = from_date ):
            #filter from the product_status_as_of
            purchase_status = product_status_as_of.filter(name = item.name)

            #filter from the sales_status_as_of
            sale_status = sales_status_as_of.filter(name = item.name)

            #product has both purchase_status and sale_status in that period
            if (purchase_status[0]['purchases_as_of'] is not None) and (sale_status[0]['sales_as_of'] is not None):
                    items.append({'name':item.name ,'selling_price':item.selling_price,'available_quantity': (item.available_quantity) - (purchase_status[0]['purchases_as_of'] + sale_status[0]['sales_as_of']) })


            #product has only purchase_status in that period
            elif (purchase_status[0]['purchases_as_of'] is not None):
                print('excetuted elseif1')
                items.append({'name':item.name ,'selling_price':item.selling_price,'available_quantity': (item.available_quantity) -(purchase_status[0]['purchases_as_of']) })

                #product has only sale_status in that period
            elif (sale_status[0]['sales_as_of'] is not None):
                print('excetuted elseif2')
                items.append({'name':item.name ,'selling_price':item.selling_price,'available_quantity': (item.available_quantity) -(sale_status[0]['sales_as_of']) })

            #if has none
            else:
                print('excetuted else')
                items.append({'name':item.name ,'selling_price':item.selling_price,'available_quantity': (item.available_quantity) })

        print(items)
        print(Products.objects.annotate(min_purchasedate = Min('purchases__date_of_purchase')).filter(min_purchasedate__lte = from_date ).count())
        if items:
            return render(request,'manager/viewstock.html',{'items': items})
        else:
            context['error']='No results found'
            return render(request,'manager/viewstock.html',{'messages':context['error']})

manager/templates/manager/dashboard.html
{% extends 'manager/managerbase.html'%}

{% block Dashboard_active %}active{% endblock %}

{% block page_brand %}Dashboard{% endblock %}

{% block body %}

<div class="row">
  <div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
      <div class="card-header card-header-warning card-header-icon">
        <div class="card-icon">
          <i class="material-icons">content_copy</i>
        </div>
        <p class="card-category">Current month sales</p>
        <h3 class="card-title">2.222M
          <small>USH</small>
        </h3>
      </div>
      <div class="card-footer">
        <div class="stats">
          <!-- <i class="material-icons text-danger">warning</i> -->
          <!-- <a href="#pablo">Get More Space...</a> -->
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
      <div class="card-header card-header-success card-header-icon">
        <div class="card-icon">
          <i class="material-icons">store</i>
        </div>
        <p class="card-category">Revenue</p>
        <h3 class="card-title">$34,245</h3>
      </div>
      <div class="card-footer">
        <div class="stats">
          <!-- <i class="material-icons">date_range</i> Last 24 Hours -->
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
      <div class="card-header card-header-danger card-header-icon">
        <div class="card-icon">
          <i class="material-icons">info_outline</i>
        </div>
        <p class="card-category"> expenses</p>
        <h3 class="card-title">100,000</h3>
      </div>
      <div class="card-footer">
        <div class="stats">
          <!-- <i class="material-icons">local_offer</i> Tracked from Github -->
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
      <div class="card-header card-header-info card-header-icon">
        <div class="card-icon">
          <i class="fa fa-twitter"></i>
        </div>
        <p class="card-category">Monthly purchases</p>
        <h3 class="card-title">2.0M
            <small>USH</small>
        </h3>
      </div>
      <div class="card-footer">
        <div class="stats">
          <!-- <i class="material-icons">update</i> Just Updated -->
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="card card-chart">
      <div class="card-header card-header-success">
        <div class="ct-chart" id="dailySalesChart"></div>
      </div>
      <div class="card-body">
        <h4 class="card-title">Daily Sales</h4>
        <p class="card-category">
          <span class="text-success"><i class="fa fa-long-arrow-up"></i> 55% </span> increase in today sales.</p>
      </div>
      <div class="card-footer">
        <div class="stats">
          <!-- <i class="material-icons">access_time</i> updated 4 minutes ago -->
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card card-chart">
      <div class="card-header card-header-warning">
        <div class="ct-chart" id="websiteViewsChart"></div>
      </div>
      <div class="card-body">
        <h4 class="card-title">Monthly Sales</h4>
        <p class="card-category">
          <span class="text-success"><i class="fa fa-long-arrow-up"></i> 55% </span> increase in today sales.
      </p>
      </div>
      <div class="card-footer">
        <div class="stats">
          <i class="material-icons">access_time</i> campaign sent 2 days ago
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card card-chart">
      <div class="card-header card-header-danger">
        <div class="ct-chart" id="completedTasksChart"></div>
      </div>
      <div class="card-body">
        <h4 class="card-title">Annual Sales</h4>
        <p class="card-category">
            <span class="text-success"><i class="fa fa-long-arrow-up"></i> 55% </span> increase in today sales.
        </p>
      </div>
      <div class="card-footer">
        <div class="stats">
          <i class="material-icons">access_time</i> campaign sent 2 days ago
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
      <div class="col-lg-6 col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Tasks</h4>
                  <p class="card-category">Tasks as per date</p>
                </div>

                <div class="card-body">
                  <!-- <div class="tab-content"> -->
                    <!-- <div class="tab-pane active" id="profile"> -->

                      <ul id="myUL" class="todo_list" >
                        {%for task in Currenttasks %}
                            <li>{{task}}<a href="{% url 'manager:deleteTask' task.id %}"><span class="close" >&times</span></a></li>
                        {%endfor%}
                        <!-- <li>Hit the gym</li>
                        <li>Pay bills</li>
                        <li >Meet George</li>
                        <li>Buy eggs</li>
                        <li>Read a book</li>
                        <li>Organize office</li> -->
                      </ul>
                      <form class="form" action="{% url 'manager:addTask' %}" method="post">
                        <div class="input-group border">
                          {%csrf_token%}
                          <input type="text" name="task" id="Task" class="form-control" placeholder="Add New TasK">
                          <button type="submit" class="btn btn-info btn-round btn-just-icon">
                            <i class="material-icons">add</i>
                            <div class="ripple-container"></div>
                          </button>
                        </div>
                      </form>
                    <!-- </div> -->
      <!-- </div> -->
      </div>

              </div>
            </div>


  <div class="col-lg-6 col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">

        <h4 class="card-title">Employees Stats</h4>
        <p class="card-category">All employees as per date</p>
      </div>
      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead class="text-primary">
            <th>ID</th>
            <th>Name</th>
            <th>Salary</th>
            <th>point of work</th>
          </thead>
          <tbody>
            <!-- <tr>
              <td>1</td>
              <td>Dakota Rice</td>
              <td>$36,738</td>
              <td>shop</td>
            </tr> -->
            {%for employee in Employees %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{employee}}</td>
              <td>{{employee.Salary}}UGX</td>
              <td>shop</td>
            </tr>
            {%endfor%}
            <!-- <tr>
              <td>2</td>
              <td>Minerva Hooper</td>
              <td>$23,789</td>
              <td>shop</td>
            </tr>
            <tr>
              <td>3</td>
              <td>Sage Rodriguez</td>
              <td>$56,142</td>
              <td>pump</td>
            </tr>
            <tr>
              <td>4</td>
              <td>Philip Chaney</td>
              <td>$38,735</td>
              <td>pump</td>
            </tr> -->
          </tbody>
        </table>

        <button  class="btn btn-warning pull-right" onclick="showaddEmployee()">Add new employee</button>
      </div>
    </div>
  </div>
</div>
<div class="row bg-primary">
<div class=" col-md-12" id="addEmployee">

        <div class="card bg-primary  ">
          <div class="card-header  card-header-primary emp">
            <span rel="tooltip" title="Close" class=" pull-right btn btn-danger" onclick="closeadd(this)">&times</span>
            <h4 class="card-title">ADD NEW EMPLOYEE</h4>
            <p class="card-category">please add required fields</p>
            <div class="card-body">

              <form action="{%url 'manager:addEmployee'%}" method="post">
                    {% csrf_token %}
                                              <div class="row">
                                                <div class="col-md-6">
                                                  <div class="form-group">
                                                    <label class="bmd-label-floating">Fist Name</label>
                                                    <input type="text" name="First_Name" class="form-control" required>
                                                  </div>
                                                </div>
                                                <div class="col-md-6">
                                                  <div class="form-group">
                                                    <label class="bmd-label-floating">Last Name</label>
                                                    <input type="text" name="Last_Name" class="form-control" required>
                                                  </div>
                                                </div>
                                              </div>
                                              <div class="row">
                                                <div class="col-md-12">
                                                  <div class="form-group">
                                                    <label class="bmd-label-floating">Address</label>
                                                    <input type="text" name="Address" class="form-control" required>
                                                  </div>
                                                </div>
                                              </div>
                                              <div class="row">
                                                <div class="col-md-4">
                                                  <div class="form-group">
                                                    <label class="bmd-label-floating">Contact</label>
                                                    <input type="tel" name="Contact" class="form-control" required>
                                                  </div>
                                                </div>
                                                <div class="col-md-4">
                                                  <div class="form-group">
                                                    <label class="bmd-label-floating">Country</label>
                                                    <input type="text" name="Country" class="form-control" required>
                                                  </div>
                                                </div>
                                                <div class="col-md-4">
                                                  <div class="form-group">
                                                    <label class="bmd-label-floating">Salary(USH)</label>
                                                    <input type="number" name="Salary" class="form-control" required>
                                                  </div>
                                                </div>
                                              </div>

                                              <button type="submit" class="btn btn-success pull-right">Add</button>
                                              <div class="clearfix"></div>
                                            </form>

            </div>
          </div>

        </div>

</div>
</div>

{% endblock%}

manager/templates/manager/managerbase.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'cashier/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'cashier/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Material Dashboard by TOTAL KINONI
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'cashier/css/material-dashboard.css' %}" rel="stylesheet" />
  <link href="{% static 'manager/css/managercss.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'cashier/demo/demo.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="{% static 'cashier/img/sidebar-1.jpg' %}">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
        <a href="/manager" class="simple-text logo-normal">
          TOTAL KINONI
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item {% block Dashboard_active %}{% endblock %}  ">
            <a class="nav-link" href="/manager">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <!-- <li class="nav-item {% block user_profile_active %}{% endblock %} ">
            <a class="nav-link" href="/manager/user">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
          </li> -->
          <li class="nav-item {% block managecashiers_active %}{% endblock %}">
              <a class="nav-link" href="/manager/managecashiers">
                <i class="material-icons">people</i>
                <p>Manage Cashiers</p>
              </a>
            </li>
          <li class="nav-item {% block transaction_active %}{% endblock %} ">
            <a class="nav-link" href="/manager/transaction">
              <i class="material-icons">money</i>
              <p>Transactions</p>
            </a>
          </li>
          <li class="nav-item {% block managestock_active %}{% endblock %} ">
            <a class="nav-link" href="/manager/managestock">
              <i class="material-icons">content_copy</i>
              <p>Manage Stock</p>
            </a>
          </li>

          <!-- <li class="nav-item ">
            <a class="nav-link" href="manager/reports">
              <i class="material-icons">content_copy</i>
              <p>Reports</p>
            </a>
          </li> -->
          <li class="nav-item ">
            <a class="nav-link" href="./notifications.html">
              <i class="material-icons">add</i>
              <p>Others</p>
            </a>
          </li>
          <!-- <li class="nav-item active-pro ">
                <a class="nav-link" href="./upgrade.html">
                    <i class="material-icons">unarchive</i>
                    <p>Upgrade to PRO</p>
                </a>
            </li> -->
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">{% block page_brand %}{% endblock %}</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown" hidden>
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">person</i>{{username}}
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login:logout' %}" >
                  <i class="material-icons">arrow_forward</i>
                  <p class="d-lg-none d-md-block">
                    Logout
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          {% block body %}
          {% endblock%}
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <!-- <nav class="float-left">
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  TOTAL KINONI
                </a>
              </li>
              <li>
                <a href="https://creative-tim.com/presentation">
                  About Us
                </a>
              </li>
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
              <li>
                <a href="https://www.creative-tim.com/license">
                  Licenses
                </a>
              </li>
            </ul>
          </nav> -->
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>
            <!--  -->
            <h6>TOTAL KINONI</h6>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'cashier/javascript/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'cashier/javascript/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'cashier/javascript/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'cashier/javascript/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <script src="{% static 'manager/javascript/managerjavascript.js' %}"></script>
  <script src="{% static 'cashier/javascript/core/cashierjavascript.js' %}"></script>
  <!-- Chartist JS -->
  <script src="{% static 'cashier/javascript/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'cashier/javascript/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'cashier/javascript/material-dashboard.min.js' %}" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'cashier/demo/demo.js' %}"></script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>
</body>

</html>