cashier/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static

app_name = 'cashier'

urlpatterns = [
#cashier/
    url(r'^$',views.index,name='index'),
    url(r'^enter_reciept/$',views.enter_reciept,name='enter_reciept'),
    url(r'^expenses/$',views.expenses, name='expenses'),
    url(r'^add_sales/$',views.add_sales, name='add_sales'),
    url(r'^enter_reciept/add_item/$',views.add_item, name='add_item'),
    url(r'^add_item/uploadcsvfile$',views.uploadcsvfile, name='uploadedfile'),

]

login/urls.py
# from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import user_logout,user_login

app_name = 'login'

urlpatterns = [
        url(r'^$',user_login,name='login'),
        url(r'^logout',user_logout,name='logout'),
]

supermarket/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^cashier/', include('cashier.urls')),
    url(r'^manager/',include('manager.urls')),
    url(r'^',include('login.urls')),
    url(r'^admin/', admin.site.urls),
]

cashier/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    name = models.CharField(max_length = 250)
    selling_price = models.IntegerField()
    available_quantity = models.IntegerField()

    def __str__(self):
        return self.name

class Sales(models.Model):
    product_in_sales = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity_sold = models.IntegerField()
    date_of_sale = models.DateField(auto_now_add=True)
    total_amount = models.IntegerField()



class Purchases(models.Model):
    product_in_purchases = models.ForeignKey(Products, on_delete=models.CASCADE)
    Cost_price = models.IntegerField()
    quantity_purchased = models.IntegerField()
    date_of_purchase = models.DateField(auto_now_add=True)
    total = models.IntegerField(default=0)

# class Expenses(models.Model):

cashier/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Products , Sales , Purchases
from datetime import date

from .functions.cashierfunctions import functions
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):

    products = Products.objects.all()
    username = request.session['username']
    # return render(request, '')
    return render(request,'cashier/index.html',{ 'products' : products, 'username':username})

@login_required
def enter_reciept(request):
    username = request.session['username']
    if request.method!='GET':
            prod = Products.objects.all()
            item_name = request.POST.getlist('item_name')
            item_cost_price =request.POST.getlist('item_cost_price')
            item_quantity =request.POST.getlist('item_quantity')
            today = str(date.today())
            req=request.POST
            for i in range(len(item_name)):
                st = item_name[i].strip()
                product = Products.objects.get(name = st)
                product.available_quantity = int(product.available_quantity) + int(item_quantity[i])
                product.save()

                # update the database
                try:
                    selected_product_purchase = product.purchases_set.get(date_of_purchase=today)
                except (KeyError, Purchases.DoesNotExist):
                    product.purchases_set.create(Cost_price = int(item_cost_price[i]),quantity_purchased = int(item_quantity[i]),total=(int(item_cost_price[i])* int(item_quantity[i])))
                else:
                    selected_product_purchase.quantity_purchased = int(selected_product_purchase.quantity_purchased) + int(item_quantity[i])
                    selected_product_purchase.item_cost_price = int(item_cost_price[i])
                    selected_product_purchase.total += (int(item_quantity[i])*int(item_cost_price[i]))
                    selected_product_purchase.save()
            # return HttpResponseRedirect(reverse('cashier:enter_reciept'))
            return render(request,'cashier/enter_reciept.html',{'products':prod, 'req':req,'username':username})

    else:
        prod = Products.objects.all()
        return render(request,'cashier/enter_reciept.html',{'products':prod,'username':username})

@login_required
def expenses(request):
    username = request.session['username']
    if request.method=='GET':
        return render(request,'cashier/expenses.html',{'username':username})
    else:

        return HttpResponseRedirect(reverse('cashier:expenses'))

@login_required
def add_sales(request):

    if request.method!='GET':
        # prod = Products.objects.all()
        item = request.POST.getlist('item')
        quantity=request.POST.getlist('quantity')
        total_amount=request.POST.getlist('total')
        today = str(date.today())
        st=''
        for i in range(len(item)):
            st = item[i].strip()
            product = Products.objects.get(name = st)
            product.available_quantity = int(product.available_quantity) - int(quantity[i])
            product.save()
            # update the database
            try:
                selected_product_sale = product.sales_set.get(date_of_sale=today)
            except (KeyError, Sales.DoesNotExist):
                product.sales_set.create(quantity_sold = quantity[i], total_amount=total_amount[i])
            else:
                selected_product_sale.quantity_sold = int(selected_product_sale.quantity_sold) + int(quantity[i])
                selected_product_sale.total_amount = int(selected_product_sale.total_amount) + int(total_amount[i])
                selected_product_sale.save()
        # return render(request,'cashier/index.html',{'products':prod ,'st': st})
        return HttpResponseRedirect(reverse('cashier:index',))

@login_required
def add_item(request):
    username = request.session['username']
    if request.method=='GET':
        return render(request,'cashier/add_item.html',{'username':username})

    else:
        newItem = functions.addnewitem(request.POST['item_name'],request.POST['item_selling_price'])
        if newItem:
            return HttpResponseRedirect(reverse('cashier:enter_reciept'))


@login_required
def uploadcsvfile(request):
    uploadedfile= request.FILES['uploadedcsvfile']
    functions.handle_uploaded_file(uploadedfile)
    return HttpResponseRedirect(reverse('cashier:add_item'))

cashier/templates/cashier/add_item.html
{% extends 'cashier/base.html' %}

{% block Reciept_active %} active {% endblock %}

{% block page_brand %}Add New Item{% endblock %}

{% block body %}

<div class="row">
                      <div class="col-md-12">
                        <div class="card">
                          <div class="card-header card-header-primary">
                            <h4 class="card-title">ADD NEW ITEM</h4>
                            <p class="card-category">ADD</p>
                          </div>
                          <div class="card-body">
                            <form action="" method="post">
                              {% csrf_token %}
                              <div class="row">

                                <div class="col-md-5">
                                  <div class="form-group">
                                    <label class="bmd-label-floating">ITEM NAME</label>
                                    <input type="text" name="item_name" class="form-control" required>
                                  </div>
                                </div>
                                <div class="col-md-4">
                                  <div class="form-group">
                                    <label class="bmd-label-floating">SELLING PRICE</label>
                                    <input type="number" name="item_selling_price" class="form-control" required>
                                  </div>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label class="bmd-label-floating">COST PRICE</label>
                                    <input type="number" name="item_cost_price" class="form-control" required>
                                  </div>
                                </div>

                              </div>



                              <button type="submit" class="btn btn-success pull-right">ADD</button>
                              <div class="clearfix"></div>
                            </form>
                          </div>
                        </div>
                      </div>

                    <div class="col-md-4">
                      <button class="btn btn-success pull-right" onclick="showupload()">Import from CSV</button>
                      <div class="clearfix"></div>
                      <div id="upload-invisible" >
                        <form action="{% url 'cashier:uploadedfile'%}" method="post" enctype="multipart/form-data">
                          <!-- <div class="form-group"> -->
                          {% csrf_token %}
                            UPLOAD (data should be arrangend in <strong>name,selling price,available quantity</strong> order)
                            <input type="file" name="uploadedcsvfile"  required>
                            <button type="submit" class="btn btn-success btn-sm">upload</button>
                            <div class="clearfix"></div>
                          <!-- </div> -->
                        </form>
                      </div>
                    </div>
      </div>

{% endblock %}

cashier/templates/cashier/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8" />


    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'cashier/img/apple-icon.png' %}"/>
    <link rel="icon" type="image/png" href="{% static 'cashier/img/favicon.png' %}"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
      Material Dashboard by TOTAL KINONI
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="{% static 'cashier/css/material-dashboard.css' %}" rel="stylesheet" />
    <link href="{% static 'cashier/css/style.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'cashier/demo/demo.css' %}" rel="stylesheet" />
  </head>

  <body class="">
    <div class="wrapper ">
      <div class="sidebar" data-color="purple" data-background-color="white" data-image="{% static 'cashier/img/sidebar-1.jpg' %}">
        <!--
          Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

          Tip 2: you can also add an image using data-image tag
      -->
        <div class="logo">
          <a href="/cashier" class="simple-text logo-normal">
            TOTAL KINONI
          </a>
        </div>
        <div class="sidebar-wrapper">
          <ul class="nav">
            <li class="nav-item {% block dashboard_active %}{% endblock %}  ">
              <a class="nav-link" href="/cashier">
                <i class="material-icons">dashboard</i>
                <p>Dashboard</p>
              </a>
            </li>

            <li class="nav-item {% block Reciept_active %}{% endblock %} ">
              <a class="nav-link" href="/cashier/enter_reciept/">
                <i class="material-icons">book</i>
                <p>Enter new Reciept</p>
              </a>
            </li>

            <li class="nav-item {% block Expenses_active %}{% endblock %} ">
              <a class="nav-link" href="/cashier/expenses/">
                <i class="material-icons">money</i>
                <p>Expenses And Damages</p>
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="/cashier/eports/">
                <i class="material-icons">content_copy</i>
                <p>Reports</p>
              </a>
            </li>
            <!-- <li class="nav-item active-pro ">
                  <a class="nav-link" href="./upgrade.html">
                      <i class="material-icons">unarchive</i>
                      <p>Upgrade to PRO</p>
                  </a>
              </li> -->
          </ul>
        </div>
      </div>
      <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
          <div class="container-fluid">
            <div class="navbar-wrapper">
              <a class="navbar-brand" href="#pablo">{% block page_brand %}{% endblock %}</a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>


            </button>
            <div class="collapse navbar-collapse justify-content-end">

              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="#pablo">
                    <i class="material-icons">dashboard</i>
                    <p class="d-lg-none d-md-block">
                      Stats
                    </p>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#pablo">
                    <i class="material-icons">person</i>{{username}}
                    <p class="d-lg-none d-md-block">
                      Account
                    </p>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login:logout' %}" >
                    <i class="material-icons">arrow_forward</i>
                    <p class="d-lg-none d-md-block">
                      Logout
                    </p>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
          <div class="container-fluid">
              {% block body %}
              {% endblock%}
          </div>
        </div>
        <footer class="footer">
          <div class="container-fluid">

            <div class="copyright float-right">
              &copy;
              <script>
                document.write(new Date().getFullYear())
              </script>
              <!--  -->
              <h6>ssematebrian2067@gmail.com</h6>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <!--   Core JS Files   -->
    <script src="{% static 'cashier/javascript/core/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'cashier/javascript/core/popper.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'cashier/javascript/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'cashier/javascript/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
    <script src="{% static 'cashier/javascript/core/cashierjavascript.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'cashier/javascript/plugins/bootstrap-notify.js' %}"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="{% static 'cashier/javascript/material-dashboard.min.js' %}" type="text/javascript"></script>
    <!-- Material Dashboard DEMO methods, don't include it in your project! -->
    <script src="{% static 'cashier/demo/demo.js' %}"></script>
    <script>
      $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        md.initDashboardPageCharts();

      });
    </script>
</body>

</html>

cashier/templates/cashier/enter_reciept.html
{% extends 'cashier/base.html' %}

{% block Reciept_active %} active {% endblock %}

{% block page_brand %}Reciepts{% endblock %}

{% block body %}

<div class="row">

  <div class="col-md-10">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Enter New Reciept</h4>
        <p class="card-category">For new items use the add item button</p>
      </div>
      <div class="card-body">
        <div class="clearfix"></div>
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-info">

              <th>
                item
              </th>
              <th>
                Cost Price
              </th>
              <th>
                Quantity(pcs)
              </th>
              <th>

            </th>
            </thead>
            <tbody>
              <tr>

                <td>
                  <input list="items_available" type="text" name="item" id="" placeholder="add item name">
                  <datalist id="items_available">
                        {%if products%}
                           {%for product in products%}
                           <option value="{{product.name}}">
                           {%endfor%}
                        {%endif%}
                    </datalist>
                </td>
                <td>
                  <input type="number" name="cost" id="">
                </td>
                <td>
                  <input type="number" name="quanity" id="">
                </td>
                <td class="text-primary">
                  <button type="submit" rel="tooltip" onclick="add_to_reciept(this)" title="Add To Reciept" class="btn pull-right btn-success btn-link btn-sm">
                                <i class="material-icons">done</i>
                    </button>
                </td>
              </tr>

            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2">
        <a href="add_item/"><button class="btn btn-warning"><i class="material-icons">add</i>Add New Item</button></a>
        <div class="clearfix"></div>
  </div>

</div>
<div class="row">
    <div class="col-md-10">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title ">View New Reciept</h4>
          <p class="card-category">Verify and Confirm</p>
        </div>
        <div class="card-body">
          <form class="" action="" method="post">
            {%csrf_token%}
            <button type="submit" class="btn btn-success pull-right" rel="tooltip" title="Confirm Reciept"><i class="material-icons">done</i>Confirm Reciept</button>
            <div class="clearfix"></div>

            <div class="table-responsive">
              <table class="table" id="reciept_view">
                <thead class=" text-info">

                  <th>
                    item
                  </th>
                  <th>
                    Cost Price
                  </th>
                  <th>
                    Quantity(pcs)
                  </th>
                  <th>
                      TOTAL
                </th>
                </thead>
                <tbody>

                </tbody>
              </table>
              <button class="btn  pull-right" id="reciept_total" rel="tooltip" title="Reciept Total"></button>
              <div class="clearfix"></div>
            </div>

          </form>


        </div>
        {{req}}
      </div>
    </div>
</div>


{% endblock %}

cashier/templates/cashier/expenses.html
{% extends 'cashier/base.html' %}

{% block Expenses_active %}active{% endblock %}

{% block page_brand %}Expenses And Damages {% endblock %}

{% block body %}

<div class="row">

  <div class="col-md-11">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title ">Enter New Reciept</h4>
        <p class="card-category">For new items use the add item button</p>
      </div>
      <div class="card-body">
        <div class="clearfix"></div>
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-info">

              <th>
                item
              </th>
              <th>
                Reason
              </th>
              <th class="Amount" id="amount">
                Amount
              </th>
              <th class="expiry" id="Expiry">
                Expiry Date
            </th>
            <th>

            </th>
            </thead>
            <tbody>
              <tr>
                <td>
                  <input type="text" name="item_name" id="" placeholder="add item name" class="form-control">
                </td>
                <td>

                <label for="expense">Expense</label>  <input type="radio" name="Reason" id="expense" onclick="clickExpenses()" >
                <label for="expiry">Expiry</label>  <input type="radio" name="Reason" id="expiry" onclick="clickExpiry()">

                </td>

                <td id="amount-expense">
                  <input type="number" name="Amount-expense" class="form-control">
                </td>
                <td id="expiry-date">
                  <input type="date" name="Expiry-date" class="form-control" >
                </td>
                <td>
                  <button type="submit" rel="tooltip" title="Add" class="btn pull-right btn-success  btn-sm">
                                <i class="material-icons">done</i>Add
                    </button>
                </td>
              </tr>

            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>

</div>

{% endblock%}

cashier/templates/cashier/index.html
{% extends 'cashier/base.html' %}

{% block dashboard_active %}active{% endblock %}

{% block page_brand %}Shop Sales Point{% endblock %}

{% block body %}
<div class="row">

<div class="col-md-6" id="sales_rt">
  <div class="card">
    <div class="card-header card-header-primary">
      <h4 class="card-title ">Shop Sales</h4>
      <p class="card-category">Sales Table</p>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <form action="/cashier/add_sales/" method="post" >
          {% csrf_token %}
        <table class="table" id="sales_table">
          <thead class=" text-primary">
            <th>
              ID
            </th>
            <th>
              Name
            </th>
            <th>
              Cost
            </th>
            <th>
              Quantity
            </th>
            <th>
              TOTAL
            </th>
          </thead>
          <tbody>

          </tbody>
        </table>
        <button type="submit" rel="tooltip" title="Confirm Sale" class="btn pull-right btn-success btn-link btn-sm">
                      <i class="material-icons">done</i>
          </button>
          </form>
        <div class="btn btn-primary pull-right" id="sales_total">TOTAL</div>
        <div class="clearfix"></div>

      </div>
    </div>
  </div>
</div>

<div class="col-md-6">
   <div class="card">
     <div class="card-header card-header-primary">
       <h4 class="card-title pull-left ">Shop Sales</h4>
       <form class="navbar-form pull-right">
          <div class="input-group no-border">
            <input type="text" value="" id="search_input" onkeyup = " mysearch('search_input','items_table',1) " class="form-control" placeholder="Search for item...">
            <button type="submit" class="btn btn-white btn-round btn-just-icon">
              <i class="material-icons">search</i>
              <div class="ripple-container"></div>
            </button>
          </div>
        </form>
     </div>
     <div class="card-body">
       <div class="table-responsive">
         <table class="table" id="items_table">
           <thead class=" text-primary">
             <th>
               No.
             </th>
             <th>
               Name
             </th>
             <th>
                Price
             </th>
             <th>
                Available
             </th>

           </thead>
           <tbody>
             {%if products%}

                {%for product in products%}
                    <tr>
                      <td>
                        {{forloop.counter}}
                      </td>
                      <td>
                        {{product.name}}
                      </td>
                      <td>
                        {{product.selling_price}}
                      </td>
                      <td>
                        {{product.available_quantity}}
                      </td>
                    </tr>
                {%endfor%}

             {%endif%}
           </tbody>
         </table>

         <div class="clearfix"></div>

       </div>
     </div>

   </div>
 <!-- {{st}} -->
</div>

</div>
{% endblock %}